### ISSUE TITLE
ros noetic下报错

### ISSUE THREAD

**Issue by chenzhengxi** [liuguitao/AVP-SLAM-PLUS#1]
在ros noetic下跑，报这个错误
Failed to build tree: parent link [base_link] of joint [camera1_joint] not found.  This is not valid according to the URDF spec. Every link you refer to from a joint needs to be explicitly defined in the robot description. To fix this problem you can either remove this joint [camera1_joint] from your urdf file, or add "<link name="base_link" />" to your urdf file.

**Comment by liuguitao** [comment]
sorry, I haven't check its performance on ros noetic.

**Comment by marquistj13** [comment]
@chenzhengxi 把urdf文件夹下两个 .xacro'文件中所有的xacro宏调用改一下，这个错误就没了，也不用改几个地方。
1. robot_with_realsense.urdf.xacro
    第七行的`<robot_body/>` 改为 `<xacro:robot_body/>`
2. robot_body.urdf.xacro
    同理，这个文件中xacro宏调用部分也加上加上xacro：前缀就行了，例如：
   ```xml
        <xacro:wheel lr="right"  translateY="1" />
        <xacro:wheel lr="left"  translateY="-1" />
        <xacro:caster fb="front"  translateX="-1" />
   ```
   以及好几个inertial matrix的调用，例如`<xacro:sphere_inertial_matrix  m="${caster_mass}" r="${caster_radius}" />`

**Comment by loseyourself-gan** [comment]
@marquistj13  你好，我是在ubuntu20上运行这个代码，还遇到了这样的错误，请问你知道怎么解决吗
**[ WARN] [1656073391.886172034]: link 'base_link' material 'red' undefined.
[ WARN] [1656073391.890221560]: link 'base_link' material 'red' undefined.
[ WARN] [1656073391.890858250]: link 'xMark_link' material 'white' undefined.
[ WARN] [1656073391.890945537]: link 'xMark_link' material 'white' undefined.
[ WARN] [1656073391.891066648]: link 'yMark_link' material 'black' undefined.
[ WARN] [1656073391.891121184]: link 'yMark_link' material 'black' undefined.**
process[mapping-9]: started with pid [56383]
[ INFO] [1656073393.474801800]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1656073393.477936783]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1656073393.873358, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1656073393.891419, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1656073393.938645663]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1656073393.944015284]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1656073394.565632388]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1656073394.648893448, 1825.830000000]: Physics dynamic reconfigure ready.
[INFO] [1656073394.807110, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1656073395.811110037, 1826.074000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1656073395.817253946, 1826.074000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1656073395.823388225, 1826.074000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1656073395.829772635, 1826.074000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[INFO] [1656073395.862120, 1826.074000]: Spawn status: SpawnModel: Successfully spawned entity
**[ERROR] [1656073396.009793923, 1826.074000000]: Unsupported Gazebo ImageFormat

[ERROR] [1656073396.011285690, 1826.074000000]: Unsupported Gazebo ImageFormat**

**Comment by b4l8** [comment]
> yMark_link



> @marquistj13 你好，我是在ubuntu20上运行这个代码，还遇到了这样的错误，请问你知道怎么解决吗 **[ WARN] [1656073391.886172034]: link 'base_link' material 'red' undefined. [ WARN] [1656073391.890221560]: link 'base_link' material 'red' undefined. [ WARN] [1656073391.890858250]: link 'xMark_link' material 'white' undefined. [ WARN] [1656073391.890945537]: link 'xMark_link' material 'white' undefined. [ WARN] [1656073391.891066648]: link 'yMark_link' material 'black' undefined. [ WARN] [1656073391.891121184]: link 'yMark_link' material 'black' undefined.** process[mapping-9]: started with pid [56383] [ INFO] [1656073393.474801800]: Finished loading Gazebo ROS API Plugin. [ INFO] [1656073393.477936783]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting... [INFO] [1656073393.873358, 0.000000]: Loading model XML from ros parameter robot_description [INFO] [1656073393.891419, 0.000000]: Waiting for service /gazebo/spawn_urdf_model [ INFO] [1656073393.938645663]: Finished loading Gazebo ROS API Plugin. [ INFO] [1656073393.944015284]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting... [ INFO] [1656073394.565632388]: waitForService: Service [/gazebo/set_physics_properties] is now available. [ INFO] [1656073394.648893448, 1825.830000000]: Physics dynamic reconfigure ready. [INFO] [1656073394.807110, 0.000000]: Calling service /gazebo/spawn_urdf_model [ INFO] [1656073395.811110037, 1826.074000000]: Camera Plugin: Using the 'robotNamespace' param: '/' [ INFO] [1656073395.817253946, 1826.074000000]: Camera Plugin (ns = /) <tf_prefix_>, set to "" [ INFO] [1656073395.823388225, 1826.074000000]: Camera Plugin: Using the 'robotNamespace' param: '/' [ INFO] [1656073395.829772635, 1826.074000000]: Camera Plugin (ns = /) <tf_prefix_>, set to "" [INFO] [1656073395.862120, 1826.074000]: Spawn status: SpawnModel: Successfully spawned entity **[ERROR] [1656073396.009793923, 1826.074000000]: Unsupported Gazebo ImageFormat
> 
> [ERROR] [1656073396.011285690, 1826.074000000]: Unsupported Gazebo ImageFormat**

material用大写Red,White,Black, ImageFormat 用R8G8B8

**Comment by scottymax** [comment]
请问noetic下跑通代码以后，有6个image的topic但是都没有数据，小车也控制不了是什么情况。。gazebo环境里压根就没有小车。。
