### ISSUE TITLE
生成的地图，pcd文件不对

### ISSUE THREAD

**Issue by w-jinkui** [liuguitao/AVP-SLAM-PLUS#10]
![2022-06-23 20-30-45屏幕截图](https://user-images.githubusercontent.com/22999222/175299337-4a5dd1be-ef36-4bde-bf5f-5c7e97e4b988.png)
请问是哪里的参数配置没有打开吗?为何我跑一遍程序后在data里生成的地图总是一个多边形？
以下是调试信息。
PARAMETERS
 * /IcpEuclideanFitnessEpsilon: 0.001
 * /IcpMaxCorrespondenceDistance: 20
 * /IcpMaximumIterations: 100
 * /IcpTransformationEpsilon: 1e-10
 * /InvalidColorThresh: 60
 * /K: [337.208441096804...
 * /R0: [0, 1.0, 0, 0.0, ...
 * /T0: [0, 0.56, 0.0]
 * /cameraRealiableDis: 8
 * /closePointThresh: 0.1
 * /farPointThresh: 20
 * /gazebo/enable_ros_network: True
 * /icpFitnessScoreThresh: 0.3
 * /imageColIncrease: 4
 * /imageRowIncrease: 2
 * /mapSave: True
 * /mapSaveLocation: /home/wangjinkui/...
 * /ndtFitnessScoreThresh: 0.3
 * /ndtResolution: 1.0
 * /ndtTransformationEpsilon: 0.01
 * /odomKeyFramDisThresh: 1.0
 * /pointCloudLeafSize: 0.1
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50.0
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /rotateDeg1: -1.0471975512
 * /rotateDeg2: -2.09439510239
 * /rotateDeg3: -3.14159265359
 * /rotateDeg4: 2.09439510239
 * /rotateDeg5: 1.0471975512
 * /skyColor: 178
 * /useICP: False
 * /useNDT: True
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    mapping (avp_slam_plus/mapping)
    pointCloudFromRGB (avp_slam_plus/pointCloudFromRGB)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [10793]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8810229c-f2ef-11ec-9cb9-b46bfc7f4fea
process[rosout-1]: started with pid [10811]
started core service [/rosout]
process[gazebo-2]: started with pid [10818]
process[gazebo_gui-3]: started with pid [10823]
process[joint_state_publisher-4]: started with pid [10828]
process[robot_state_publisher-5]: started with pid [10829]
process[urdf_spawner-6]: started with pid [10830]
process[rviz-7]: started with pid [10835]
process[pointCloudFromRGB-8]: started with pid [10837]
process[mapping-9]: started with pid [10839]
[ INFO] [1655987115.746995464]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1655987115.750255709]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1655987115.833215969]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1655987115.836173538]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1655987116.230643, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1655987116.254208, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1655987116.260347, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1655987116.269821114]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1655987116.291300, 1825.799000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name robot

**Comment by 123Bruceche** [comment]
So am I

**Comment by 123Bruceche** [comment]
@liuguitao

**Comment by liuguitao** [comment]
Did you control vehicle motion？
if you just let vehicle stop, then it will just generate a  small map.
how to control vehicle motion, you can refer to readme.

**Comment by 123Bruceche** [comment]
感谢您的回复，显示map 这个frame不存在，导致rviz不正常，无论怎么移动最后都是生成的一个规则的多边形，应该是八边形。我应该调整哪里了。


Thank you for your reply, show map this frame does not exist, resulting in rviz is not normal, no matter how you move the end is generated a regular polygon, should be an octagon. Where should I adjust?


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月14日(周日) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuguitao/AVP-SLAM-PLUS] 生成的地图，pcd文件不对 (Issue #10)




 
Did you control vehicle motion？
 if you just let vehicle stop, then it will just generate a  small map.
 how to control vehicle motion, you can refer to readme.
