### ISSUE TITLE
你好，我在noetic上跑通了代码，roslaunch后没有显示小车的模型，相机的topic也没有数据，但是没有报错

### ISSUE THREAD

**Issue by scottymax** [liuguitao/AVP-SLAM-PLUS#12]
log如下：
 roslaunch avp_slam_plus slamRGB.launch 
... logging to /root/.ros/log/4fbde08a-2433-11ed-b991-d85ed32f568d/roslaunch-shenjiacheng-Z590-GAMING-X-1622957.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://shenjiacheng-Z590-GAMING-X:46725/

SUMMARY
========

PARAMETERS
 * /IcpEuclideanFitnessEpsilon: 0.001
 * /IcpMaxCorrespondenceDistance: 20
 * /IcpMaximumIterations: 100
 * /IcpTransformationEpsilon: 1e-10
 * /InvalidColorThresh: 60
 * /K: [337.208441096804...
 * /R0: [0, 1.0, 0, 0.0, ...
 * /T0: [0, 0.56, 0.0]
 * /cameraRealiableDis: 8
 * /closePointThresh: 0.1
 * /farPointThresh: 20
 * /gazebo/enable_ros_network: True
 * /icpFitnessScoreThresh: 0.3
 * /imageColIncrease: 4
 * /imageRowIncrease: 2
 * /mapSave: True
 * /mapSaveLocation: /mnt/sjc_workspac...
 * /ndtFitnessScoreThresh: 0.3
 * /ndtResolution: 1.0
 * /ndtTransformationEpsilon: 0.01
 * /odomKeyFramDisThresh: 1.0
 * /pointCloudLeafSize: 0.1
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50.0
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /rotateDeg1: -1.0471975511965976
 * /rotateDeg2: -2.0943951023931953
 * /rotateDeg3: -3.141592653589793
 * /rotateDeg4: 2.0943951023931953
 * /rotateDeg5: 1.0471975511965976
 * /skyColor: 178
 * /useICP: False
 * /useNDT: True
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    mapping (avp_slam_plus/mapping)
    pointCloudFromRGB (avp_slam_plus/pointCloudFromRGB)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [1622974]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4fbde08a-2433-11ed-b991-d85ed32f568d
process[rosout-1]: started with pid [1622984]
started core service [/rosout]
process[gazebo-2]: started with pid [1622991]
process[gazebo_gui-3]: started with pid [1622995]
process[joint_state_publisher-4]: started with pid [1623000]
process[robot_state_publisher-5]: started with pid [1623002]
process[urdf_spawner-6]: started with pid [1623003]
process[rviz-7]: started with pid [1623004]
process[pointCloudFromRGB-8]: started with pid [1623005]
process[mapping-9]: started with pid [1623011]
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[INFO] [1661403832.860590, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1661403832.867019, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1661403832.923459101]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1661403832.924257138]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1661403832.991150598]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1661403832.992010511]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1661403834.047507709, 1825.804000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1661403834.072742, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1661403834.110467642, 1825.865000000]: Physics dynamic reconfigure ready.
[INFO] [1661403834.239540, 1825.971000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1661403834.255844258, 1825.971000000]: Starting plugin DiffDrive(ns = //)
[ INFO] [1661403834.255958825, 1825.971000000]: DiffDrive(ns = //): <rosDebugLevel> = Debug
[ INFO] [1661403834.257063601, 1825.971000000]: DiffDrive(ns = //): <tf_prefix> = 
[DEBUG] [1661403834.257130804, 1825.971000000]: DiffDrive(ns = //): <commandTopic> = cmd_vel
[DEBUG] [1661403834.257150965, 1825.971000000]: DiffDrive(ns = //): <odometryTopic> = odom
[DEBUG] [1661403834.257164804, 1825.971000000]: DiffDrive(ns = //): <odometryFrame> = odom
[DEBUG] [1661403834.257178969, 1825.971000000]: DiffDrive(ns = //): <robotBaseFrame> = base_footprint
[DEBUG] [1661403834.257223146, 1825.971000000]: DiffDrive(ns = //): <publishWheelTF> = true
[ WARN] [1661403834.257243125, 1825.971000000]: DiffDrive(ns = //): missing <publishOdomTF> default is true
[DEBUG] [1661403834.257265865, 1825.971000000]: DiffDrive(ns = //): <publishWheelJointState> = true
[DEBUG] [1661403834.257326302, 1825.971000000]: DiffDrive(ns = //): <wheelSeparation> = 0.59999999999999998
[DEBUG] [1661403834.257349700, 1825.971000000]: DiffDrive(ns = //): <wheelDiameter> = 0.12
[DEBUG] [1661403834.257368468, 1825.971000000]: DiffDrive(ns = //): <wheelAcceleration> = 1.8
[DEBUG] [1661403834.257386434, 1825.971000000]: DiffDrive(ns = //): <wheelTorque> = 30
[DEBUG] [1661403834.257402254, 1825.971000000]: DiffDrive(ns = //): <updateRate> = 100
[ WARN] [1661403834.257451387, 1825.971000000]: DiffDrive(ns = //): missing <odometrySource> default is 1
[DEBUG] [1661403834.257488104, 1825.971000000]: DiffDrive(ns = //): <leftJoint> = base_to_wheel_left_joint
[urdf_spawner-6] process has finished cleanly
log file: /root/.ros/log/4fbde08a-2433-11ed-b991-d85ed32f568d/urdf_spawner-6*.log

**Comment by scottymax** [comment]
![图片](https://user-images.githubusercontent.com/44422324/186580037-5cd19bda-bcf1-4d54-8c4e-96323be0aec6.png)

**Comment by 13572320829** [comment]
我和你情况一样，没有小车，但是有报错，我还没解决

**Comment by CiaranYoung** [comment]
系统升级了，我现在也在noetic上跑代码，但是catkin_make的时候报了很多错，请问楼主遇到过吗

**Comment by lijh1024** [comment]
[urdf_spawner-5] process has finished cleanly
log file: /.ros/log/d515c1d8-5423-11ed-b0c5-4d020f40fd42/urdf_spawner-5*.log
我也一样，rviz没有数据显示，没有小车模型，请问解决了吗

**Comment by scottymax** [comment]
已经解决，需要更改urdf文件

**Comment by andyxiao2022** [comment]
@scottymax Did you solve this problem? Could you send me the urdf file?

**Comment by ZYJxxx** [comment]
@scottymax 要更改地方呢？
