### ISSUE TITLE
mapping中没有闭环功能

### ISSUE THREAD

**Issue by dzh00443103** [liuguitao/AVP-SLAM-PLUS#2]
mapping中没看到有闭环功能？

**Comment by liuguitao** [comment]
The version of  opensource now  hasn't this function.
I will release  the version of having loopclosure soon.

**Comment by dzh00443103** [comment]
你好，邮件已收到。

**Comment by andyxiao2022** [comment]
@liuguitao Hello guitao, can I have this loop-closure code?

**Comment by dzh00443103** [comment]
你好，邮件已收到。
