### ISSUE TITLE
您好，按您的步骤，出现这个很奇怪的报错，百思不得其解。

### ISSUE THREAD

**Issue by Christoo1** [liuguitao/AVP-SLAM-PLUS#3]
![图片](https://user-images.githubusercontent.com/54760160/148875312-12339265-3bea-4150-aa53-2394a24c26b8.png)

**Comment by Christoo1** [comment]
@liuguitao

**Comment by liuguitao** [comment]
please jump to "catkin_ws"  folder, then execute the command

**Comment by Christoo1** [comment]
![图片](https://user-images.githubusercontent.com/54760160/148887867-dc24a7e6-2d0f-4916-a48c-e52955229cb9.png)
I tried, but it still can't work，Is it my environment configuration problem？

**Comment by liuguitao** [comment]
what is "base"  mean? could you exit "base", then try again.
roslaunch avp_slam_plus slamRGB.launch , could this command work?

**Comment by Christoo1** [comment]
![图片](https://user-images.githubusercontent.com/54760160/148932994-aeb59caf-1f8e-4ffe-9638-b606c3bbb32d.png)
'base' is the default environment of the system，when i run 'roslaunch avp_slam_plus slamRGB.launch ' command. it works. strangely enough!

**Comment by liuguitao** [comment]
then , Is  localization function success?

**Comment by liuguitao** [comment]
I am sorry that there is an error in readme.md.
I have correct it.
the localization command should be
roslaunch avp_slam_plus  localizationRGB.launch.
not
roslaunch avp_slam_plus  localizaitonRGB.launch.
very sorry!

**Comment by Christoo1** [comment]
Never mind！with the new command, it works! thanks！
