### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by guowenjing5** [liuguitao/AVP-SLAM-PLUS#4]
when I follow the installization guilds, I met this problem:
"Could NOT find gazebo_ros_control (missing: gazebo_ros_control_DIR)
Could not find the required component 'gazebo_ros_control'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found. 
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package): 
 Could not find a package configuration file provided by  
"gazebo_ros_control" with any of the following names:
    gazebo_ros_controlConfig.cmake
    gazebo_ros_control-config.cmake        "

could you please help me fix this problem?

**Comment by liuguitao** [comment]
try
sudo apt-get install ros-kinetic-gazebo-ros-control
