### ISSUE TITLE
Getting incorrect slam result, when using roslaunch avp_slam_plus slamRGB.launch

### ISSUE THREAD

**Issue by ChunHsuehLee** [liuguitao/AVP-SLAM-PLUS#6]
![Screenshot from 2022-03-22 21-07-06](https://user-images.githubusercontent.com/93879365/159602060-007768f9-e9a2-49a3-b0dd-22721d220f26.png)

I got a result like this when I am running roslaunch avp_slam_plus slamRGB.launch. 

There's also some error showing in the terminal. 
![Screenshot from 2022-03-22 21-12-07](https://user-images.githubusercontent.com/93879365/159602919-4840bd89-a728-47de-b87a-d0bce78fbe4c.png)

Please let me know if there's any solution to this issue. 

Thanks in advance!

**Comment by liuguitao** [comment]
try again, please!

**Comment by liuguitao** [comment]
terminal error, don't care it
