### ISSUE TITLE
[ERROR] : Unsupported Gazebo ImageFormat

### ISSUE THREAD

**Issue by loseyourself-gan** [liuguitao/AVP-SLAM-PLUS#9]
Hello, Thanks for your open source code.
I run roslaunch avp_slam_plus slamRGB.launch on ubuntu20.04.
I met the error like this. could you help me ?
Thanks a lot.

setting /run_id to ccdf6336-ec52-11ec-a227-6f46fcf89108
process[rosout-1]: started with pid [99339]
started core service [/rosout]
process[gazebo-2]: started with pid [99354]
process[gazebo_gui-3]: started with pid [99359]
process[joint_state_publisher-4]: started with pid [99364]
process[robot_state_publisher-5]: started with pid [99365]
process[urdf_spawner-6]: started with pid [99368]
process[rviz-7]: started with pid [99373]
process[pointCloudFromRGB-8]: started with pid [99377]
[ WARN] [1655260093.366230375]: link 'base_link' material 'red' undefined.
process[mapping-9]: started with pid [99380]
**[ WARN] [1655260093.370139822]: link 'base_link' material 'red' undefined.
[ WARN] [1655260093.373411814]: link 'xMark_link' material 'white' undefined.
[ WARN] [1655260093.373475971]: link 'xMark_link' material 'white' undefined.
[ WARN] [1655260093.373570737]: link 'yMark_link' material 'black' undefined.
[ WARN] [1655260093.373623964]: link 'yMark_link' material 'black' undefined.**
[INFO] [1655260094.332368, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1655260094.351609, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1655260095.000981028]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1655260095.004058315]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1655260095.346666465]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1655260095.349617059]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1655260096.282615681]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1655260096.447414737, 1825.838000000]: Physics dynamic reconfigure ready.
[INFO] [1655260096.479189, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1655260097.419402014, 1825.986000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1655260097.426992448, 1825.986000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1655260097.436112553, 1825.986000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1655260097.445444441, 1825.986000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[INFO] [1655260097.484072, 1825.986000]: Spawn status: SpawnModel: Successfully spawned entity
### **[ERROR] [1655260097.658475486, 1825.986000000]: Unsupported Gazebo ImageFormat

[ERROR] [1655260097.660442247, 1825.986000000]: Unsupported Gazebo ImageFormat**

**Comment by sunrish** [comment]
hi,do you fixed it ,i met the same problem

**Comment by liuguitao** [comment]
I tested it in melodic ubuntu18, it is good.
check your log, I think maybe gazebo version is different between melodic and noetic.

**Comment by ShanLN** [comment]
I've got the same problem "Unsupported Gazebo ImageFormat". My version is ubuntu18.04 + gazebo9.16.0  
any suggestions ?

**Comment by ShanLN** [comment]
Ignore my question. I find the error "Unsupported Gazebo ImageFormat" didn't effect the process. I can still control the car with  control keyboard ~

**Comment by andyxiao2022** [comment]
> Ignore my question. I find the error "Unsupported Gazebo ImageFormat" didn't effect the process. I can still control the car with control keyboard ~

Hello ShanLN, @ShanLN  can you see the robot moving in the Gazebo. The speed changes, but I could not see the robot moving in the Gazebo. I could not see the six camera images.
